### ISSUE TITLE
maven install 打包的包无法启动

### ISSUE THREAD

**Issue by venyowong** [lets-blade/blade#108]
在构建完 Hello World 项目后，使用 maven install 打包，用 java -jar test.jar 运行，报错：
```
Exception in thread "_(:3」∠)_" java.lang.ExceptionInInitializerError
        at com.blade.server.netty.NettyServer.start(NettyServer.java:85)
        at com.blade.Blade.lambda$start$1(Blade.java:261)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.blade.mvc.Const.<clinit>(Const.java:13)
        ... 3 more
```
\<dependency\>
	    \<groupId\>com.bladejava\</groupId\>
	    \<artifactId\>blade-mvc\</artifactId\>
	    \<version\>2.0.0\</version\>
	\</dependency\>
  \</dependencies\>
```

**Comment by hellokaton** [comment]
打包命令是 `mvn clean package`，你可以试试下载 https://github.com/bladejava/first-blade-app 这个`Hello world` 例子打包
