### ISSUE TITLE
com.blade.exception.TemplateException: java.lang.ClassCastException: [B cannot be cast to [C

### ISSUE THREAD

**Issue by paoding-team** [lets-blade/blade#160]
- jdk.version: 9.0.1 
- blade-mvc: 2.0.5

```java
Caused by: java.lang.ClassCastException: [B cannot be cast to [C
	at jetbrick.template.parser.ast.AstText$Jdk6CharArrayEncoder.<init>(AstText.java:281)
	at jetbrick.template.parser.ast.AstText.execute(AstText.java:217)
	at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
	at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
	at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
	at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
	at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:103)
```

**Comment by hellokaton** [comment]
Hi @jagopy , please use java8 version, there are many unknown issues in java9, there are many unknowns in java9, and we're not yet compatible.
