### ISSUE TITLE
maven 打包后 运行模板引擎 异常

### ISSUE THREAD

**Issue by shan333chao** [lets-blade/blade#206]
```java
2018-03-06 18:00:19:628 INFO - [ nio-worker@ thread-1 ] c.b.m.h.RequestExecution  | HTTP/1.1    GET     /
2018-03-06 18:00:19:811 INFO - [ nio-worker@ thread-1 ] j.t.JetEngineImpl         | JetEngine.version = 2.1.5
2018-03-06 18:00:19:812 INFO - [ nio-worker@ thread-1 ] j.t.JetEngineImpl         | JetEngine.loader = jetbrick.template.loader.ClasspathResourceLoader, root = /templates                                                                                                     /, reload = true
2018-03-06 18:00:19:826 INFO - [ nio-worker@ thread-1 ] j.t.r.c.ClassResolver     | import package: java.lang.*
2018-03-06 18:00:19:826 INFO - [ nio-worker@ thread-1 ] j.t.r.c.ClassResolver     | import package: java.util.*
2018-03-06 18:00:19:835 INFO - [ nio-worker@ thread-1 ] j.t.r.m.MethodInvokerResolver | import 38 methods from class jetbrick.template.runtime.buildin.JetMethods
2018-03-06 18:00:19:838 INFO - [ nio-worker@ thread-1 ] j.t.r.f.FunctionInvokerResolver | import 11 functions from class jetbrick.template.runtime.buildin.JetFunctions
2018-03-06 18:00:19:840 INFO - [ nio-worker@ thread-1 ] j.t.r.t.TagInvokerResolver | import 2 tags from class jetbrick.template.runtime.buildin.JetTags
2018-03-06 18:00:19:856 INFO - [ nio-worker@ thread-1 ] j.t.r.GlobalResolver      | Scanning @JetMethods, @JetFunctions, @JetTags implements from [com.cheduhui] ...
2018-03-06 18:00:19:880 INFO - [ nio-worker@ thread-1 ] j.t.r.GlobalResolver      | Found 0 annotated classes, time elapsed 23 ms.
2018-03-06 18:00:19:941 INFO - [ nio-worker@ thread-1 ] j.t.JetTemplateImpl       | Loading template: index.html
2018-03-06 18:00:20:212 ERROR - [ nio-worker@ thread-1 ] c.b.m.h.HttpResponse      | render error
com.blade.exception.TemplateException: java.lang.ClassCastException: [B cannot be cast to [C
        at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:105)
        at com.blade.mvc.http.HttpResponse.render(HttpResponse.java:198)
        at com.blade.mvc.http.Response.render(Response.java:274)
        at com.blade.mvc.handler.RequestExecution.handle(RequestExecution.java:179)
        at com.blade.mvc.handler.RequestExecution.routeHandle(RequestExecution.java:142)
        at com.blade.mvc.handler.RequestExecution.run(RequestExecution.java:108)
        at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:26)
        at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:18)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: [B cannot be cast to [C
        at jetbrick.template.parser.ast.AstText$Jdk6CharArrayEncoder.<init>(AstText.java:281)
        at jetbrick.template.parser.ast.AstText.execute(AstText.java:217)
        at jetbrick.template.parser.ast.AstStatementList.execute(AstStatementList.java:212)
        at jetbrick.template.parser.ast.AstTemplate.execute(AstTemplate.java:37)
        at jetbrick.template.JetTemplateImpl.doInterpret(JetTemplateImpl.java:160)
        at jetbrick.template.JetTemplateImpl.render(JetTemplateImpl.java:141)
        at com.blade.mvc.view.template.JetbrickTemplateEngine.render(JetbrickTemplateEngine.java:103)
        ... 42 more

```

**调试环境正常运行**

>  运行jar包后 用到模板的都会出现这个问题，求助

**Comment by ccqy66** [comment]
请问你用的jdk版本是java8吗？

**Comment by shan333chao** [comment]
莫名其妙 本地jdk 自动升级到了 java9
切换到java8  一切正常
