### ISSUE TITLE
这个版本maven install一直编译不过

### ISSUE THREAD

**Issue by zzhignore** [lets-blade/blade#210]
```java
testListenAddress(com.blade.BladeTest)  Time elapsed: 5.836 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/http/client/methods/HttpGet
	at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
	at com.blade.BladeTest.testListenAddress(BladeTest.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
```

**Comment by hellokaton** [comment]
Try `mvn clean install -DskipTests`

**Comment by zzhignore** [comment]
用这个打出来的包，用在tale这个项目上，会报初始化异常
2018-03-13 09:32:18:737 WARN - [ nio-worker@ thread-1 ] i.n.c.ChannelInitializer  | Failed to initialize a channel. Closing: [id: 0xdec562a8, L:/127.0.0.1:80 - R:/127.0.0.1:57625]
java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpServerCodec

**Comment by hellokaton** [comment]
```java
java.lang.NoClassDefFoundError: io/netty/handler/codec/http/HttpServerCodec
```

已经提示你了

**Comment by zzhignore** [comment]
是提示了，但是这个框架会缺这个包，不是框架的问题吗？

**Comment by hellokaton** [comment]
@zzhignore 这个不是框架的问题，你可以追溯的，通过打包后的文件来查看。但你给的信息不足，我没法通过几行文字看到更具体的情况 :) 比如打包后的情况。
