### ISSUE TITLE
Windows Paths.get InvalidPathException: Illegal char <:> 

### ISSUE THREAD

**Issue by kassadin** [lets-blade/blade#217]
Windows 10  Java 8

blade-demos 任意项目运行后报错

```
Exception in thread "watch@thread" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /D:/IdeaProjects/blade-demos/blade-vue-todolist/target/classes/
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.blade.watcher.EnvironmentWatcher.run(EnvironmentWatcher.java:27)
	at java.lang.Thread.run(Thread.java:748)
```
![tim 20180331142239](https://user-images.githubusercontent.com/1104051/38160411-e1db4594-34ef-11e8-9ac8-611f503b0930.png)
![tim 20180331142317](https://user-images.githubusercontent.com/1104051/38160412-e23b0d9e-34ef-11e8-8539-97be7a4fa849.png)

**Comment by hellokaton** [comment]
感谢你的反馈，正在重现这个问题，稍后给你答复。

**Comment by ccqy66** [comment]
获取类路径可以使用Blade.class.getResource("")

**Comment by hellokaton** [comment]
@ccqy66  `Blade.class.getResource("")` 获取的是当前类字节码所在位置，这个问题是在 Windows 环境下获取 `CLASSPATH` 路径异常导致，因为要同时兼容 `jar` 包模式、调试模式、分离打包模式，目前只需要根据 [Java NIO file path issue](https://stackoverflow.com/questions/9834776/java-nio-file-path-issue) 修复它，在下一个版本中将正常，我正在 windows 环境下调试 😃
