### ISSUE TITLE
LocalDateTime 在@JSON时会抛出异常.

### ISSUE THREAD

**Issue by chenshun00** [lets-blade/blade#228]
异常栈如下：

```java
2018/05/06 19:53:47 ERROR [   worker@threadㄧ2 ]      c.b.k.j.DefaultJsonSupport : object to json string error java.lang.IllegalArgumentException: 2018-05-06T19:53:47.070
	at com.blade.kit.json.SampleJsonSerializer.serialize(SampleJsonSerializer.java:61)
	at com.blade.kit.json.SampleJsonSerializer.serialize(SampleJsonSerializer.java:38)
	at com.blade.kit.json.SampleJsonSerializer.serialize(SampleJsonSerializer.java:38)
	at com.blade.kit.json.DefaultJsonSupport.toString(DefaultJsonSupport.java:26)
	at com.blade.kit.json.DefaultJsonSupport.toString(DefaultJsonSupport.java:14)
	at com.blade.kit.JsonKit.toString(JsonKit.java:42)
	at com.blade.mvc.http.Response.json(Response.java:220)
	at com.blade.mvc.handler.RequestExecution.handle(RequestExecution.java:188)
	at com.blade.mvc.handler.RequestExecution.routeHandle(RequestExecution.java:155)
	at com.blade.mvc.handler.RequestExecution.run(RequestExecution.java:114)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:26)
	at com.blade.server.netty.HttpServerHandler.channelRead0(HttpServerHandler.java:18)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:73)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chenshun00** [comment]
并且测试过  `fastJson` 是正常的

**Comment by hellokaton** [comment]
@chenshun00 可以发一下被序列化的数据结构吗?

**Comment by chenshun00** [comment]
```
    @Test
    public void testLocal(){
        Map<String,Object> result = new HashMap<>(8);
        result.put("date", LocalDateTime.now());
        System.out.println(JsonKit.toString(result));
    }
```
我翻看了源代码，好像是对 `LocalDateTime` 没有判断类型
