### ISSUE TITLE
Missing some dependencies 

### ISSUE THREAD

**Issue by daimajia** [lets-blade/blade#23]
```

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/servlet/http/HttpSessionIdListener
    at org.eclipse.jetty.server.session.SessionHandler.<clinit>(SessionHandler.java:54)
    at org.eclipse.jetty.servlet.ServletContextHandler.newSessionHandler(ServletContextHandler.java:241)
    at org.eclipse.jetty.servlet.ServletContextHandler.getSessionHandler(ServletContextHandler.java:334)
    at org.eclipse.jetty.servlet.ServletContextHandler.relinkHandlers(ServletContextHandler.java:180)
    at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:157)
    at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:117)
    at org.eclipse.jetty.servlet.ServletContextHandler.<init>(ServletContextHandler.java:105)
    at com.blade.server.Server.start(Server.java:60)
    at com.blade.Blade.start(Blade.java:629)
    at com.blade.Blade.start(Blade.java:639)
    at App.main(App.java:13)

```

**Comment by hellokaton** [comment]
I see your `pom.xml`

**Comment by daimajia** [comment]
I use IntelliJ IDEA to solve the dependencies instead of `pom.xml`, the following is my dependency settings: 

![image](https://cloud.githubusercontent.com/assets/2503423/11947409/3625940c-a8a1-11e5-8d82-3aa7c046be71.png)

**Comment by daimajia** [comment]
![image](https://cloud.githubusercontent.com/assets/2503423/11947423/7013edd0-a8a1-11e5-9eb7-001fe99bd0b8.png)

**Comment by hellokaton** [comment]
Add this dependency to your project

``` xml
<dependency>
    <groupId>com.bladejava</groupId>
    <artifactId>blade-startup</artifactId>
    <version>1.0.1</version>
</dependency>
```

Because the start depend on the jetty service.

The IDE with can be anything, as long as the project is a standard maven type, you can refer to [https://github.com/bladejava/hello](https://github.com/bladejava/hello)

**Comment by daimajia** [comment]
@biezhi Thanks. I solved this problem following your instruction.
