### ISSUE TITLE
post json decodeHexByte 

### ISSUE THREAD

**Issue by shan333chao** [lets-blade/blade#250]
**controller**

```java
@PostRoute("/orders")
@JSON
public ResponseBase updateOrders(@BodyParam  OrderRequest req) {
    ResponseBase<Boolean> saveOrder = new ResponseBase<Boolean>();
    if (req==null){
        saveOrder.error();
        saveOrder.setCode(ResCode.IllegalArgument.getcode());
    }
    paymentService.saveOrders(req.getList(),req.getAlimamaAccount());
    saveOrder.success();
    return saveOrder;
}
```

**postbody**

```java
public class OrderRequest {
    private String alimamaAccount;
    private ArrayList<OrderRo> list;
}

public class OrderRo {
    //创建时间
    private LocalDateTime createTime;
    // 点击时间
    private LocalDateTime clickTime;
    // 商品信息
    private String productInfo;
    //'商品ID
    private String productId;
    //'掌柜旺旺
    private String wangwangName;
    //'所属店铺
    private String shopName;
    //'商品数
    private Float procuctCount;
    //'商品单价
    private BigDecimal productPrice;
    /**
     *ORDER_PAY("订单付款", 1),
     ORDER_INVALD("订单失效", 2),
     ORDER_BILL("订单结算",3),
     ORDER_SUCCESS("订单成功",4);
     */
    @BeanIgnore
    private String orderStatusStr;

    /**
     * ORDER_PAY("订单付款", 1),
     ORDER_INVALD("订单失效",2),
     ORDER_BILL("订单结算",3);
     */
    @BeanIgnore
    private String orderTypeStr;

    private Integer  orderStatus;
    private Integer orderType;
    // 收入比率
    private String incomePercent;
    // 分成比率
    private String getPercent;
    // 付款金额
    private BigDecimal payPrice;
    // 效果预估
    private BigDecimal estimatedEffect;
    // 结算金额
    private BigDecimal billPrice;
    // 预估收入
    private BigDecimal estimatedRevenue;
    // 结算时间
    private String billTime;
    // 佣金比率
    private String commissionRate;
    // 佣金金额
    private BigDecimal commissionAmount;
    // 补贴比率
    private String subsidyRatio;
    // 补贴金额
    private BigDecimal subsidyAmount;
    // 补贴类型
    private String subsidyType;
    // 成交平台
    private String dealingPlatform;
    // 第三方服务来源
    private String thirdServiceSource;
    // 订单编号
    private String orderId;
    // 类目名称
    private String cate;
    // 来源媒体ID
    private String mediaId;
    // 来源媒体名称
    private String mediaName;
    // 广告位ID
    private String adId;
    //广告位名称
    private String adName;
}
```

**请求内容**

```json
{
    "list": [
             {
            "createTime": "2018-06-16 09:47:06",
            "clickTime": "2018-06-16 09:41:01",
            "productInfo": "\u3010\u72c2\u6b22\u4ef7\u3011\u7231\u9e2d\u719f\u98df\u5c0f\u5403\u9ebb\u8fa3\u9e2d\u7fc535g&times;15\u5305\u5364\u5473\u96f6\u98df\u771f\u7a7a\u88c5\u4f11\u95f2\u96f6\u98df",
            "productId": "527092752911",
            "wangwangName": "\u7231\u9e2d\u98df\u54c1\u65d7\u8230\u5e97",
            "shopName": "\u7231\u9e2d\u98df\u54c1\u65d7\u8230\u5e97",
            "procuctCount": 1.0,
            "productPrice": 100.0,
            "orderStatusStr": "\u8ba2\u5355\u4ed8\u6b3e",
            "orderTypeStr": "\u805a\u5212\u7b97",
            "incomePercent": "2.00 %",
            "getPercent": "100.00 %",
            "payPrice": 13.08,
            "estimatedEffect": 0.27,
            "billPrice": 0.0,
            "estimatedRevenue": 0.0,
            "billTime": "",
            "commissionRate": "1.50 %",
            "commissionAmount": 0.0,
            "subsidyRatio": "0.50 %",
            "subsidyAmount": 0.0,
            "subsidyType": "\u5929\u732b",
            "dealingPlatform": "\u65e0\u7ebf",
            "thirdServiceSource": "--",
            "orderId": "179004923251216232",
            "cate": "\u98df\u54c1-\u96f6\u98df/\u7279\u4ea7",
            "mediaId": "45798219",
            "mediaName": "\u8fd4\u5229\u8d2d_10_\u673a\u5668\u4eba",
            "adId": "676184983",
            "adName": "\u8fd4\u5229\u8d2d_10_\u673a\u5668\u4eba"
        }, {
            "createTime": "2018-06-16 09:47:06",
            "clickTime": "2018-06-16 09:41:01",
            "productInfo": "\u3010\u72c2\u6b22\u4ef7\u3011\u7231\u9e2d\u719f\u98df\u5c0f\u5403\u9ebb\u8fa3\u9e2d\u7fc535g&times;15\u5305\u5364\u5473\u96f6\u98df\u771f\u7a7a\u88c5\u4f11\u95f2\u96f6\u98df",
            "productId": "527092752911",
            "wangwangName": "\u7231\u9e2d\u98df\u54c1\u65d7\u8230\u5e97",
            "shopName": "\u7231\u9e2d\u98df\u54c1\u65d7\u8230\u5e97",
            "procuctCount": 1.0,
            "productPrice": 100.0,
            "orderStatusStr": "\u8ba2\u5355\u4ed8\u6b3e",
            "orderTypeStr": "\u805a\u5212\u7b97",
            "incomePercent": "2.00 %",
            "getPercent": "100.00 %",
            "payPrice": 13.08,
            "estimatedEffect": 0.27,
            "billPrice": 0.0,
            "estimatedRevenue": 0.0,
            "billTime": "",
            "commissionRate": "1.50 %",
            "commissionAmount": 0.0,
            "subsidyRatio": "0.50 %",
            "subsidyAmount": 0.0,
            "subsidyType": "\u5929\u732b",
            "dealingPlatform": "\u65e0\u7ebf",
            "thirdServiceSource": "--",
            "orderId": "179004923251216232",
            "cate": "\u98df\u54c1-\u96f6\u98df/\u7279\u4ea7",
            "mediaId": "45798219",
            "mediaName": "\u8fd4\u5229\u8d2d_10_\u673a\u5668\u4eba",
            "adId": "676184983",
            "adName": "\u8fd4\u5229\u8d2d_10_\u673a\u5668\u4eba"
        }
    ],
    "alimamaAccount": "\u7389\u4e66"
}
```

**异常信息**

```java
Caused by: java.lang.IllegalArgumentException: invalid hex byte '",' at index 488 of 'times;15\u5305\u5364\u5473\u96f6\u98df\u771f\u7a7a\u88c5\u4f11\u95f2\u96f6\u98df",
            "productId": "527092752911",
            "wangwangName": "\u7231\u9e2d\u98df\u54c1\u65d7\u8230\u5e97",
            "shopName": "\u7231\u9e2d\u98df\u54c1\u65d7\u8230\u5e97",
            "procuctCount": 1.0,
            "productPrice": 100.0,
            "orderStatusStr": "\u8ba2\u5355\u4ed8\u6b3e",
            "orderTypeStr": "\u805a\u5212\u7b97",
            "incomePercent": "2.00 %",
            "getPercent": "100.00 %",
            "payPrice": 13.08,
            "estimatedEffect": 0.27,
            "billPrice": 0.0,
            "estimatedRevenue": 0.0,
            "billTime": "",
            "commissionRate": "1.50 %",
            "commissionAmount": 0.0,
            "subsidyRatio": "0.50 %",
            "subsidyAmount": 0.0,
            "subsidyType": "\u5929\u732b",
            "dealingPlatform": "\u65e0\u7ebf",
            "thirdServiceSource": "--",
            "orderId": "179004923251216232",
            "cate": "\u98df\u54c1-\u96f6\u98df/\u7279\u4ea7",
            "mediaId": "45798219",
            "mediaName": "\u8fd4\u5229\u8d2d_10_\u673a\u5668\u4eba",
            "adId": "676184983",
            "adName": "\u8fd4\u5229\u8d2d_10_\u673a\u5668\u4eba"
        },    {
            "createTime": "2018-06-16 09:47:06",
            "clickTime": "2018-06-16 09:41:01",
            "productInfo": "\u3010\u72c2\u6b22\u4ef7\u3011\u7231\u9e2d\u719f\u98df\u5c0f\u5403\u9ebb\u8fa3\u9e2d\u7fc535g'
	at io.netty.util.internal.StringUtil.decodeHexByte(StringUtil.java:234)
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:351)
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:309)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.decodeAttribute(HttpPostStandardRequestDecoder.java:628)
	... 47 more
```

单独提交一个订单数据是正常的，提交两个就会解析json失败

```java
at io.netty.util.internal.StringUtil.decodeHexByte(StringUtil.java:234)
```

**Comment by hellokaton** [comment]
@shan333chao  感谢你的反馈，我正在重现这个问题。

**Comment by hellokaton** [comment]
这是一个隐藏的 bug，你目前可以使用 `2.0.9-SNAPSHOT` 这个快照版本来避免这个异常。
[这里](https://github.com/lets-blade/blade/commit/b24679293ac5fd5552ab759764657781c67e8a22#diff-6c754842ef59ff5927867181598d4358R86) 防止了当一个 `json` 请求来的时候解析 `form` 表单导致解码失败（netty 认为这是一个2位的16进制字符）。

**Comment by shan333chao** [comment]
2018/06/16 17:50:24  INFO [           thread- ]             c.b.s.n.NettyServer : environment.jdk.version    => 1.8.0_91
2018/06/16 17:50:24  INFO [           thread- ]             c.b.s.n.NettyServer : environment.user.dir       => ...
2018/06/16 17:50:24  INFO [           thread- ]             c.b.s.n.NettyServer : environment.java.io.tmpdir => ...
2018/06/16 17:50:24  INFO [           thread- ]             c.b.s.n.NettyServer : environment.user.timezone  => Asia/Shanghai
2018/06/16 17:50:24  INFO [           thread- ]             c.b.s.n.NettyServer : environment.file.encoding  => UTF-8
2018/06/16 17:50:24  INFO [           thread- ]             c.b.s.n.NettyServer : environment.classpath      => ...
faligo
Exception in thread "thread-" java.lang.NoClassDefFoundError: org/slf4j/impl/Ansi
	at com.blade.kit.BladeKit.logAddRoute(BladeKit.java:337)
	at com.blade.mvc.route.RouteMatcher.lambda$register$7(RouteMatcher.java:312)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at com.blade.mvc.route.RouteMatcher.register(RouteMatcher.java:312)
	at com.blade.server.netty.NettyServer.initIoc(NettyServer.java:141)
	at com.blade.server.netty.NettyServer.start(NettyServer.java:118)
	at com.blade.Blade.lambda$start$1(Blade.java:698)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.Ansi
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
更新了快照版本2.0.9-SNAPSHOT  后 这个类找不到org/slf4j/impl/Ansi ，然后单独导包 1.7.25 还没好

**Comment by hellokaton** [comment]
```bash
mvn clean compile -U
```

强制拉一下依赖试试。

快照版本的依赖需要加入

```xml
<repository>
    <id>snapshots-repo</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <releases>
        <enabled>false</enabled>
    </releases>
    <snapshots>
        <enabled>true</enabled>
    </snapshots>
</repository>
```

**Comment by shan333chao** [comment]
添加了这个包 好了
`        <dependency>
            <groupId>com.bladejava</groupId>
            <artifactId>blade-log</artifactId>
            <version>0.1.5</version>
        </dependency>`

**Comment by hellokaton** [comment]
@shan333chao 这个包是 Blade 强制依赖的，不用单独添加啊

**Comment by shan333chao** [comment]
可是不添加就一直是
`Exception in thread "thread-" java.lang.NoClassDefFoundError: org/slf4j/impl/Ansi`
