### ISSUE TITLE
筛选要执行的的method逻辑不严谨

### ISSUE THREAD

**Issue by iWuYc** [lets-blade/blade#258]
> blade-mvc-2.0.9.ALPHA1-sources.jar!/com/blade/server/netty/RouteMethodHandler.java:200
在该行中，对指定的方法进行执行，但如果有如下的情况，会出现无法正确识别方法的问题。
```java
    @GetRoute(TaleConst.REGISTER)
    public String register(Request request) {
    ......
    }
    @PostRoute(TaleConst.REGISTER)
    @JSON
    public RestResponse<?> register(SweetPersonParam sweetPersonParam) {
    .....
    }
```
原因是：调用了下面的这个方法进行执行方法的筛选：
```java
com.blade.reflectasm.MethodAccess#getIndex(java.lang.String, int)
```
该方法在遇到入参数量一致的方法就直接返回了，并没有对参数列表进行检查，导致ClassCaseException的错误。
麻烦维护组确认下……

**Comment by hellokaton** [comment]
感谢你的关注，这个问题已经得到修复，暂未 `push`

**Comment by iWuYc** [comment]
请问该问题关闭是已经提交了吗？我去看了下，好像最新的2.0.9.BETA2并未解决该问题，是准备正式版再提交吗？

**Comment by hellokaton** [comment]
@iWuYc-X 你在最新版本可以重现吗？可以发一段代码，`tale` 项目中没有遇到这个问题。

**Comment by iWuYc** [comment]
可以重现的，我是使用您的https://github.com/otale/tale这个博客框架中发现的问题。
```java
 @GetRoute(TaleConst.REGISTER)
public String register(Request request) {
   return "regist";
}

@PostRoute(TaleConst.REGISTER)
@JSON
public RestResponse<?> register(PersonParam PersonParam) {
    return RestResponse.ok();
}

异常栈为：
```log
2018/07/17 23:14:40 ERROR [   worker@threadㄧ2 ] c.b.m.h.DefaultExceptionHandler : Request Exception java.lang.ClassCastException: com.tale.model.params.SweetPersonParam cannot be cast to com.blade.mvc.http.Request
	at com.tale.controller.admin.SweetPersonControllerMethodAccess.invoke(Unknown Source)
	at com.blade.reflectasm.MethodAccess.invoke(MethodAccess.java:43)
	at com.blade.server.netty.RouteMethodHandler.routeHandle(RouteMethodHandler.java:204)
	at com.blade.server.netty.RouteMethodHandler.handle(RouteMethodHandler.java:332)
	at com.blade.server.netty.HttpServerDispatcher.channelRead0(HttpServerDispatcher.java:67)
	at com.blade.server.netty.HttpServerDispatcher.channelRead0(HttpServerDispatcher.java:34)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:748)

```log

```

我跟踪了下，发现，在com.blade.server.netty.RouteMethodHandler#routeHandle，204行中，在blade-asm-0.03模块中有一个methodAccess.invoke的方法调用，方法里有一个getIndex方法进行方法的筛选，我建议您使用参数列表的方式进行比较，只是单独使用参数列表长度来筛选方法不够严谨，我看到在MethodAccess中就存在相应的方法public int getIndex(String methodName, Class... paramTypes)；

这是在我的代码中发现的问题，我不清楚是不是我使用错了，还有就是，我的blade没有使用您最新的代码，我自己切了个分支出来的。

**Comment by iWuYc** [comment]
贴下pom中的版本信息给你吧。
```xml
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <sqlite.version>3.21.0.1</sqlite.version>
        <blade-mvc.version>2.0.9.BETA2</blade-mvc.version>
        <anima.version>0.2.3</anima.version>
        <blade-tpl.verion>0.1.3</blade-tpl.verion>
        <commonmark.version>0.11.0</commonmark.version>
        <rome.version>1.0</rome.version>
        <emoji.version>4.0.0</emoji.version>
    </properties>
```

**Comment by hellokaton** [comment]
@iWuYc-X 找到了，这个问题确实存在，你目前的解决办法是修改一个方法名称就好了，我想想怎么优化吧，因为如果使用 `参数列表的方式进行比较` 会麻烦一些，找 `Method` 主要目的是想让走一次缓存，感谢你指出，我没有重现的原因是方法名字并不会重复。

**Comment by iWuYc** [comment]
嗯，因为这个筛选其实我之前也做过工具类，所以，我也清楚大概的问题是什么，希望你的框架越来越完善吧。之前是因为看到，你的blade做得挺简洁轻量的，所以拿过来用了。

**Comment by ccqy66** [comment]
@biezhi I have a question,`Route`contain the relation of `Path` and `Method`, when we get `Route`,can get `Method` quickly,why need `MethodAccess` to find `Method`

**Comment by hellokaton** [comment]
@ccqy66 因为 `asm` 的方式比反射执行方法效率要高，参考 [这个](https://github.com/EsotericSoftware/reflectasm) 项目。

**Comment by ccqy66** [comment]
@biezhi ok，了解了一下，的确通过asm直接生成代码，比反射性能要高很多。思考了一下解决方案，是否可以在`MethodAccess`做一个映射关系，映射`Bean`中的`Method`与`index`之间的映射。例如：
```java
public abstract class MethodAccess {
    private String[] methodNames;
    /**
    * key:原生method
    * vbalue:对应于XXXMethodAccess类中的方法下标
    */
    private Map<Method,Integer> methodNameIndexes;
}
```
查找时，可以通过Method进行查找，屏蔽相同方法名带来的问题。
ps：不知你这边有没有一些比较优雅的方式？
对此我提了一个pr：https://github.com/lets-blade/blade-asm/pull/1
