### ISSUE TITLE
Request queryAsInt is null

### ISSUE THREAD

**Issue by hellokaton** [lets-blade/blade#32]
``` java
Caused by: java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:592)
    at java.lang.Integer.valueOf(Integer.java:766)
    at com.blade.web.http.wrapper.ServletRequest.queryAsInt(ServletRequest.java:304)
```

**Comment by hellokaton** [comment]
1.5.1 was repaired.
