### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/blade/Blade

### ISSUE THREAD

**Issue by liujiaxian** [lets-blade/blade#391]
java -jar target/ljx.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/blade/Blade
	at com.sp.Application.main(Application.java:7)
Caused by: java.lang.ClassNotFoundException: com.blade.Blade
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

**Comment by LinXuanran** [comment]
Can you provide examples? Examples of this problem can reappear
