### ISSUE TITLE
Cannot start application on Mac

### ISSUE THREAD

**Issue by EdgarLGB** [lets-blade/blade#393]
Hi,

I am using Mac to develop a web app. Could you help me out of this? Why it threw this exception when trying to run application?

```
[Exception in thread "_(:3」∠)_" java.lang.NoClassDefFoundError: io/netty/channel/epoll/EpollEventLoopGroup
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.blade.ioc.reader.JarReaderImpl.getClasses(JarReaderImpl.java:94)
	at com.blade.ioc.reader.JarReaderImpl.getClassByAnnotation(JarReaderImpl.java:43)
	at com.blade.ioc.reader.AbstractClassReader.readClasses(AbstractClassReader.java:30)
	at com.blade.ioc.DynamicContext.recursionFindClasses(DynamicContext.java:41)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:269)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at com.blade.server.netty.NettyServer.initIoc(NettyServer.java:157)
	at com.blade.server.netty.NettyServer.start(NettyServer.java:131)
	at com.blade.Blade.lambda$start$1(Blade.java:855)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.epoll.EpollEventLoopGroup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 19 more]([url](`url`))
```

**Comment by ebottabi** [comment]
@EdgarLGB how are you launching the main class ?
