### ISSUE TITLE
NullPointerException when running application from jar

### ISSUE THREAD

**Issue by frodeaa** [lets-blade/blade#62]
change in https://github.com/biezhi/blade/commit/6c30faa4a12f657098bc73227b2a925f92ab4690#diff-0649f4cff8db55e74927362acbb4f3e1L62 causes NullPointerException if running the application within a jar

```
2016-03-24 15:35:39,660 ERROR [main] github.frodeaa.bottle.App | failed to start
java.lang.NullPointerException
        at com.blade.server.Server.start(Server.java:60)
        at github.frodeaa.bottle.App.main(App.java:145)

```

see https://github.com/frodeaa/bottle/tree/blade-1.6.1M1 for example

**Comment by hellokaton** [comment]
If you want to use the main function to start the service, please join this dependency

``` xml
<dependency>
    <groupId>com.bladejava</groupId>
    <artifactId>blade-startup</artifactId>
    <version>1.0.1</version>
</dependency>
```

**Comment by frodeaa** [comment]
I already have the dependency, the NullPointerException is caused by this code in com.blade.server.Server

```
        context.setResourceBase(Thread.currentThread().getContextClassLoader()  
                        .getResource("").getPath());
```

Thread.currentThread().getContextClassLoader().getResource("") is null when called from Jar

```
$ cat Test.java
public class Test {
    public static void main(String...args) {
        System.out.println(
        Thread.currentThread().getContextClassLoader().getResource("").getPath());
    }
}

$ javac Test.java && java Test
/tmp/test/

$ jar cf Test.jar Test.class 
$ java -cp Test.jar Test
Exception in thread "main" java.lang.NullPointerException
        at Test.main(Test.java:4)
```
