### ISSUE TITLE
不能jar包运行

### ISSUE THREAD

**Issue by xiaou** [lets-blade/blade#97]
编译这个库的helloworld后，maven打出jar包，
`java -jar` target/helloworld-0.0.1.jar报错：
~~~
Exception in thread "main" java.lang.NullPointerException
	at com.blade.embedd.EmbedJettyServer.<init>(EmbedJettyServer.java:61)
~~~

似乎是因为EmbedJettyServer类的构造函数里：
~~~java
if (DynamicContext.isJarContext()) {
            URL url = EmbedJettyServer.class.getResource("/");
            this.classPath = url.getPath();
~~~

即如果是jar执行，则class.getResource("/")，而这个代码在jar里是返回null的啊

**Comment by hellokaton** [comment]
`blade` 程序的打包方式是通过 `maven` 的 `assembly` 实现的，所以打包的方式不是使用 `mvn clean package`，如果你想打包一个应用可以看看 [这个](https://github.com/bladejava/sample) 例子。

**Comment by liujiaxian** [comment]
`
java.lang.NullPointerException
	at com.blade.embedd.EmbedJettyServer.<init>(EmbedJettyServer.java:65)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at com.blade.Blade.startNoJoin(Blade.java:562)
	at com.blade.Blade.start(Blade.java:531)
	at com.blade.Blade.start(Blade.java:537)
	at com.sp.Application.main(Application.java:7)
Exception in thread "main" java.lang.NullPointerException
	at com.blade.Blade.start(Blade.java:532)
	at com.blade.Blade.start(Blade.java:537)
	at com.sp.Application.main(Application.java:7)
`

怎么解决的？
